VERILOG = ../icebreaker/spectrum.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/video.v pll.v up5k_zx_rom.v up5k_zx_ram.v \
	  flash_loader.v icosoc_flashmem.v video_ram.v 

VERILOG_SIM = ../icebreaker/spectrum.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/video.v up5k_zx_rom.v up5k_zx_ram.v video_ram.v SB_SPRAM256KA.v \
	  flash_loader.v icosoc_flashmem.v sim.v sim_spiflash.v 


PIN_DEF = icebreaker.pcf

include icebreaker.mk

