VERILOG = ../icebreaker/spectrum.v  \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/video.v clock_divider.v pll.v up5k_zx_rom.v up5k_zx_ram.v \
	  ../src/osd/spi_ram_btn.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/keyboard.v \
	  video_ram.v 

VERILOG_SIM = ../icebreaker/spectrum.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/osd/spi_ram_btn.v \
	  ../src/keyboard.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/dpram.v \
	  ../src/video.v \
	  clock_divider.v up5k_zx_rom.v up5k_zx_ram.v video_ram.v SB_SPRAM256KA.v \
	  sim.v 


PIN_DEF = icebreaker.pcf

include icebreaker.mk

